### ISSUE TITLE
Practica individual Alyn Ximena Gomez Hernandez 

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-AlynGomez12#1]
[preposiciones logicas-Alyn.pdf](https://github.com/user-attachments/files/17452316/preposiciones.logicas-Alyn.pdf)

**Comment by mae18-25** [comment]
Portada:24/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:23/25
Resultados y conclusiones:24/25
Total:96/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
